---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trading
    service: kafka
  name: kafka
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
      service: kafka
  template:
    metadata:
      labels:
        app: trading
        service: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: HOST://localhost:9092,DOCKER://kafka:9093
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@localhost:9091
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: DOCKER
            - name: KAFKA_LISTENERS
              value: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
          image: us-central1-docker.pkg.dev/elastic-sa/tbekiares/kafka:$IMAGE_VERSION
          #imagePullPolicy: Never
          name: kafka
          ports:
            - containerPort: 9093
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trading
    service: kafka
  name: kafka
  namespace: trading
spec:
  ports:
    - name: kafka
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: trading
    service: kafka
---